gate_double:
  qw: 1.0
  qz: 0.0
  x: 4.0
  y: 0.0
  z: 1.2
gate_triple:
  qw: 1.0
  qz: 0.0
  x: 4.0
  y: 4.0
  z: 1.2
wp1:
  qw: 1.0
  qz: 0.0
  x: 4.0
  y: 0.0
  z: 1.2
wp2:
  qw: 1.0
  qz: 0.0
  x: 4.0
  y: 4.0
  z: 1.2
wp3:
  qw: 1.0
  qz: 0.0
  x: 4.0
  y: 6.0
  z: 1.2
wp4:
  qw: 1.0
  qz: 0.0
  x: 1148.404
  y: 1295.798
  z: 1.2
